import React, { useMemo, useState } from 'react'
import { Activity, AlertCircle, BarChart3, Bell, CalendarClock, CheckCircle2, ChevronDown, CircleHelp, Clock3, Database, Filter, GitBranch, LayoutDashboard, Mail, MessageSquare, Search, Settings2, ShieldAlert, Sparkles, Target, Users, X } from 'lucide-react'
import './styles.css'

type Priority = 'Critical' | 'High' | 'Medium'
type Item = { id: number; title: string; tag: string; owner: string; priority: Priority; score: number; due: string; source: string; status: string; impact: string; age: string }
const items: Item[] = [
  { id: 1, title: 'Production: API Timeout in Payment Service', tag: 'INCIDENT', owner: 'Priya Sharma', priority: 'Critical', score: 9.8, due: 'ASAP', source: 'Incident feed', status: 'In progress', impact: 'Customer payments', age: '18m' },
  { id: 2, title: 'Data Migration Q3 Customer Records', tag: 'JIRA', owner: 'Arjun Patel', priority: 'Critical', score: 9.2, due: 'Today · 5:00 PM', source: 'Data team channel', status: 'Blocked', impact: '12 customers', age: '42m' },
  { id: 3, title: 'Security Audit Findings Review', tag: 'TEAMS', owner: 'Priya Sharma', priority: 'High', score: 8.1, due: 'Tomorrow · 10:00 AM', source: 'Security-compliance', status: 'Needs review', impact: '12 findings', age: '1h' },
  { id: 4, title: 'Q4 Budget Approval Required', tag: 'OUTLOOK', owner: 'Finance Team', priority: 'High', score: 7.9, due: 'Today · 7:00 PM', source: 'Email', status: 'Awaiting approval', impact: '$2.4M budget', age: '2h' },
  { id: 5, title: 'Implement caching layer for Redis', tag: 'JIRA', owner: 'Vikram Roy', priority: 'Medium', score: 6.7, due: 'Sep 20', source: 'Engineering backlog', status: 'Planned', impact: 'Performance', age: '3h' },
  { id: 6, title: 'Review API documentation updates', tag: 'CONFLUENCE', owner: 'Neha Kapoor', priority: 'Medium', score: 5.8, due: 'Sep 21', source: 'Platform docs', status: 'In review', impact: 'Developer enablement', age: '4h' }
]
const members = [{ name: 'Priya Sharma', role: 'Engineering Lead', utilization: 88, avatar: 'PS', open: 4, risk: 'High' }, { name: 'Arjun Patel', role: 'Data Engineering', utilization: 78, avatar: 'AP', open: 3, risk: 'Medium' }, { name: 'Vikram Roy', role: 'Platform Engineering', utilization: 65, avatar: 'VR', open: 2, risk: 'Low' }, { name: 'Neha Kapoor', role: 'Documentation', utilization: 48, avatar: 'NK', open: 2, risk: 'Low' }]
const sources = [['Jira', 3, 30, <GitBranch size={15}/>], ['Incident Feed', 2, 20, <AlertCircle size={15}/>], ['Teams', 2, 20, <MessageSquare size={15}/>], ['Outlook', 2, 20, <Mail size={15}/>], ['Confluence', 1, 10, <Database size={15}/>]]
const risks = [['Payment service incident', 'Customer-facing API timeout', 'Critical', 'Priya Sharma'], ['Q3 migration validation', 'Customer records awaiting validation', 'Critical', 'Arjun Patel'], ['Security audit findings', 'Review required before tomorrow', 'High', 'Priya Sharma'], ['Reconciliation batch delay', 'Finance batch is 45 minutes behind SLA', 'High', 'Vikram Roy'], ['Release readiness', 'Two checklist items remain unconfirmed', 'Medium', 'Arjun Patel']]

type Member = typeof members[number]
export default function ExecutiveApp() {
  const [tab, setTab] = useState<'personal' | 'team' | 'trace'>('personal')
  const [query, setQuery] = useState('')
  const [insight, setInsight] = useState('critical')
  const [selected, setSelected] = useState<Item | null>(null)
  const [member, setMember] = useState<Member | null>(null)
  const [toast, setToast] = useState('')
  const filtered = useMemo(() => items.filter(item => `${item.title} ${item.owner} ${item.tag}`.toLowerCase().includes(query.toLowerCase())), [query])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2200) }
  const critical = items.filter(item => item.priority === 'Critical')
  const high = items.filter(item => item.priority === 'High')
  const today = items.filter(item => item.due.includes('Today') || item.due === 'ASAP')
  const rows = insight === 'today' ? today : insight === 'high' ? high : insight === 'score' ? items.slice(0, 4) : critical
  const avg = (items.reduce((sum, item) => sum + item.score, 0) / items.length).toFixed(1)
  return <div className="app-shell">
    <header className="topbar"><div className="brand"><div className="brand-mark"><Target size={19}/></div><div><div className="brand-title">NEXUS</div><div className="brand-sub">Executive Work Intelligence</div></div></div><div className="top-actions"><div className="search"><Search size={17}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search work, people, teams..." /></div><button className="icon-btn" onClick={() => notify('No new priority alerts')} title="Notifications"><Bell size={18}/><span className="notif-dot"/></button><button className="icon-btn" onClick={() => notify('Dashboard settings opened')} title="Settings"><Settings2 size={18}/></button><div className="profile"><div className="profile-avatar">PS</div><div className="profile-text"><b>Priya Sharma</b><span>Engineering · Platform</span></div><ChevronDown size={15}/></div></div></header>
    <main className="content"><div className="page-heading"><div><div className="eyebrow"><Sparkles size={14}/> PRIORITY OPERATIONS</div><h1>Work Priority Dashboard</h1><p>One view of what needs attention, why it matters, and what happens next.</p></div><div className="heading-actions"><button className="secondary-btn"><CalendarClock size={16}/> Today <ChevronDown size={14}/></button><button className="primary-btn" onClick={() => notify('Priority review started')}><Activity size={16}/> Start Priority Review</button></div></div>
      <nav className="tabs"><button className={tab === 'personal' ? 'active' : ''} onClick={() => setTab('personal')}><LayoutDashboard size={16}/> My Priority</button><button className={tab === 'team' ? 'active' : ''} onClick={() => setTab('team')}><Users size={16}/> Manager View</button><button className={tab === 'trace' ? 'active' : ''} onClick={() => setTab('trace')}><BarChart3 size={16}/> Actions &amp; Traceability</button></nav>
      {tab === 'trace' ? <Traceability rows={filtered} onSelect={setSelected}/> : <><section className="kpis"><Kpi icon={<AlertCircle/>} label={tab === 'team' ? 'Team Members' : 'Critical Items'} value={tab === 'team' ? members.length : critical.length} sub={tab === 'team' ? 'Review workload and capacity' : 'Require immediate attention'} tone="red" onClick={() => setInsight('critical')}/><Kpi icon={<ShieldAlert/>} label="High Priority" value={high.length} sub="Require attention today" tone="amber" onClick={() => setInsight('high')}/><Kpi icon={<Clock3/>} label="Today's Actions" value={today.length} sub="Due today or ASAP" tone="blue" onClick={() => setInsight('today')}/><Kpi icon={<BarChart3/>} label="Avg Priority Score" value={`${avg}/10`} sub="Confidence in ranking" tone="green" onClick={() => setInsight('score')}/></section>{tab === 'personal' ? <InsightPanel rows={rows} onSelect={setSelected} title={insight === 'today' ? 'Actions due today' : insight === 'high' ? 'High-priority delivery signals' : insight === 'score' ? 'Portfolio priority health' : 'Critical work requiring immediate attention'}/> : <><section className="panel"><div className="panel-head"><div><h2>Team Member Dashboard</h2><span>Click an employee to review their workload</span></div><span className="mini-total">{members.length} people</span></div>{members.map(person => <button className="team-row" key={person.name} onClick={() => setMember(person)}><div className="team-avatar">{person.avatar}</div><div className="team-info"><b>{person.name}</b><span>{person.role}</span></div><div className="open-work"><b>{person.open}</b><span>open</span></div><div className="util"><div className="util-label"><span>Workload</span><b>{person.utilization}%</b></div><div className="bar"><i style={{width: `${person.utilization}%`}}/></div></div><span className={`risk-chip ${person.risk.toLowerCase()}`}>{person.risk}</span><ChevronDown size={15}/></button>)}</section><div className="manager-insight-grid"><SourceDistribution/><TeamRisks/></div></>}</>}</main>
    {selected && <DetailDrawer item={selected} onClose={() => setSelected(null)} onComplete={() => { setSelected(null); notify('Action marked complete') }}/>} {member && <MemberDrawer person={member} onClose={() => setMember(null)}/>} {toast && <div className="toast"><CheckCircle2 size={17}/>{toast}</div>}<footer>Priority signals are explainable and traceable · Sources: Incident Feed, Jira, Teams, Outlook, Confluence</footer>
  </div>
}
function Kpi({icon, label, value, sub, tone, onClick}: {icon: JSX.Element; label: string; value: string | number; sub: string; tone: string; onClick: () => void}) { return <button className={`kpi ${tone}`} onClick={onClick}><div className="kpi-icon">{icon}</div><div className="kpi-copy"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></button> }
function InsightPanel({title, rows, onSelect}: {title: string; rows: Item[]; onSelect: (item: Item) => void}) { return <section className="panel insight-panel"><div className="insight-head"><div><span className="eyebrow">SELECTED PRIORITY CARD</span><h2>{title}</h2><p>{rows.length} items are currently active. Review the highest-impact signals and confirm ownership or mitigation.</p></div><div className="insight-count">{rows.length}<span>items</span></div></div><div className="insight-list">{rows.map(item => <button className="insight-row" key={item.id} onClick={() => onSelect(item)}><div className={`insight-dot ${item.priority.toLowerCase()}`}/><div><b>{item.title}</b><span>{item.owner} · {item.source}</span></div><strong>{item.score}</strong><ChevronDown size={15}/></button>)}</div></section> }
function SourceDistribution() { return <section className="panel"><div className="panel-head"><div><h2>Work Distribution by Sources</h2><span>Where the team's active work is coming from</span></div><span className="mini-total">10 items</span></div><div className="source-content">{sources.map(([name, count, percent, icon]) => <div className="source-row" key={String(name)}><div className="source-icon">{icon}</div><div className="source-name"><b>{name}</b><span>{count} active items</span></div><div className="source-bar"><i style={{width: `${percent}%`}}/></div><strong>{percent}%</strong></div>)}</div></section> }
function TeamRisks() { return <section className="panel"><div className="panel-head"><div><h2>Team Risks &amp; Blockers</h2><span>Signals that may affect delivery</span></div><span className="mini-total danger">5 open</span></div><div className="risk-list">{risks.map(([title, detail, level, owner]) => <div className="risk-row" key={title}><div className={`risk-marker ${String(level).toLowerCase()}`}/><div className="risk-main"><b>{title}</b><span>{detail}</span><small>Owner · {owner}</small></div><span className={`risk-chip ${String(level).toLowerCase()}`}>{level}</span></div>)}</div></section> }
function Traceability({rows, onSelect}: {rows: Item[]; onSelect: (item: Item) => void}) { return <section className="trace-grid"><section className="panel"><div className="panel-head"><div><h2>Action Items &amp; Traceability</h2><span>Every priority can be traced back to its source signal.</span></div><button className="filter-btn"><Filter size={15}/> All Sources <ChevronDown size={14}/></button></div>{rows.map(item => <button className="trace-row" key={item.id} onClick={() => onSelect(item)}><div className={`trace-status ${item.priority.toLowerCase()}`}/><div className="trace-main"><b>{item.title}</b><span>Source: {item.source} · Owner: {item.owner}</span></div><div className="trace-confidence"><span>Confidence</span><b>{Math.round(item.score * 9.8)}%</b></div><div className="trace-action">{item.due}</div></button>)}</section><section className="panel audit"><div className="panel-head"><div><h2>Audit Trail</h2><span>Recent priority decisions</span></div></div>{['Priority ranking updated','Data signal received','Team workload recalculated','New action created'].map((text, index) => <div className="audit-row" key={text}><time>{`09:${45 - index * 3} AM`}</time><div><b>{text}</b><span>Priority decision recorded in the activity log</span></div></div>)}</section></section> }
function DetailDrawer({item, onClose, onComplete}: {item: Item; onClose: () => void; onComplete: () => void}) { return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={event => event.stopPropagation()}><div className="drawer-head"><div><span className={`tag ${item.tag.toLowerCase()}`}>{item.tag}</span><h2>{item.title}</h2></div><button className="icon-btn drawer-close" onClick={onClose}><X size={18}/></button></div><div className="drawer-score"><div><span>Priority score</span><strong>{item.score}/10</strong></div><b className={`priority-pill ${item.priority.toLowerCase()}`}>{item.priority}</b></div><div className="detail-grid"><Detail label="Owner" value={item.owner}/><Detail label="Due" value={item.due}/><Detail label="Status" value={item.status}/><Detail label="Business impact" value={item.impact}/></div><div className="why"><h3>Why this is prioritized</h3><p>The ranking combines business impact, urgency, dependency signals, and source confidence. This item has a strong customer or delivery consequence and a time-sensitive due signal.</p></div><div className="source-box"><CircleHelp size={17}/><div><b>Traceable source</b><span>{item.source} · Signal received {item.age} ago</span></div></div><div className="drawer-actions"><button className="secondary-btn" onClick={onClose}>Keep open</button><button className="primary-btn" onClick={onComplete}><CheckCircle2 size={16}/> Mark complete</button></div></aside></div> }
function Detail({label, value}: {label: string; value: string}) { return <div><span>{label}</span><b>{value}</b></div> }
function MemberDrawer({person, onClose}: {person: Member; onClose: () => void}) { return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer" onClick={event => event.stopPropagation()}><div className="drawer-head"><div><div className="team-avatar drawer-avatar">{person.avatar}</div><h2>{person.name}</h2><span className="member-role">{person.role}</span></div><button className="icon-btn drawer-close" onClick={onClose}><X size={18}/></button></div><div className="member-summary"><div><span>Open work</span><strong>{person.open}</strong></div><div><span>Utilization</span><strong>{person.utilization}%</strong></div><div><span>Risk</span><strong>{person.risk}</strong></div></div><div className="why"><h3>Workload overview</h3><p>{person.name} currently has {person.open} open priority items and is operating at {person.utilization}% workload utilization.</p></div></aside></div> }
